trigger:
- Develop

resources:
- repo: self

pool:
  name: 'Default'
  demands:
  - agent.name -equals agentclass2

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build
    steps:

    #Build Frontend Docker Image
    - task: Docker@2
      displayName: Build Frontend Docker Image
      inputs:
        containerRegistry: 'classtrackapi'
        command: 'build'
        Dockerfile: '**/ClassTrack/Dockerfile'
        arguments: '-t classtrackapi.azurecr.io/classtrack-frontend2:latest'

    # Push Frontend Docker Image
    - task: Docker@2
      displayName: Push Frontend Docker Image
      inputs:
        containerRegistry: 'classtrackapi'
        command: 'push'
        repository: 'classtrack-frontend2'
        tags: latest

    # Deploy Frontend Container
    - task: AzureWebAppContainer@1
      displayName: Deploy Frontend Container
      inputs:
        azureSubscription: 'Azure for Students(8c757b97-b103-445f-9aa8-d6cff021ddcf)'
        appName: 'ClassTrack'
        containers: classtrackapi.azurecr.io/classtrack-frontend2:latest
        appSettings: '-Port 8081'