trigger:
- Develop

resources:
- repo: self

pool:
  name: 'Default'
  demands:
  - agent.name -equals agentclass2

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Docker Images
  jobs:
  - job: Build
    displayName: Build and Push Docker Images
    steps:

    # Build Frontend Docker Image
    - task: Docker@2
      displayName: Build Frontend Docker Image
      inputs:
        containerRegistry: 'classtrackapi'
        command: 'build'
        Dockerfile: '**/ClassTrack/Dockerfile'
        arguments: '-t classtrackapi.azurecr.io/classtrack-frontend:latest'

    # Push Frontend Docker Image
    - task: Docker@2
      displayName: Push Frontend Docker Image
      inputs:
        containerRegistry: 'classtrackapi'
        command: 'push'
        repository: 'classtrack-frontend'
        tags: latest

    # Deploy Frontend Container
    - task: AzureWebAppContainer@1
      displayName: Deploy Frontend Container
      inputs:
        azureSubscription: 'Azure for Students(8c757b97-b103-445f-9aa8-d6cff021ddcf)'
        appName: 'ClassTrack-Frontend'
        containers: classtrackapi.azurecr.io/classtrack-frontend:latest
        appSettings: '-Port 8081'


#backfuncional

        trigger:
- feature/Docker

resources:
- repo: self

pool:
  name: 'Default'
  demands:
  - agent.name -equals agentclass2

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build Backend Docker image
      inputs:
        containerRegistry: 'classtrackapi'
        command: 'build'
        Dockerfile: '**/backend/Dockerfile'
        arguments: '-t classtrackapi.azurecr.io/classtrack-api:latest'
    - task: Docker@2
      displayName: Push Backend Docker image
      inputs:
        containerRegistry: 'classtrackapi'
        command: 'push'
        repository: 'classtrack-api'
        tags: 'latest'
    - task: AzureWebAppContainer@1
      displayName: Deploy Backend Docker image to Azure Web App
      inputs:
        azureSubscription: 'Azure for Students(8c757b97-b103-445f-9aa8-d6cff021ddcf)'
        appName: 'ClassTrack-API-Alumnos2'
        containers: 'classtrackapi.azurecr.io/classtrack-api:latest'
        appSettings: '-Port 3000'
  
    #Build Frontend Docker Image
    - task: Docker@2
      displayName: Build Frontend Docker Image
      inputs:
        containerRegistry: 'classtrackapi'
        command: 'build'
        Dockerfile: '**/ClassTrack/Dockerfile'
        arguments: '-t classtrackapi.azurecr.io/classtrack-frontend:latest'

    # Push Frontend Docker Image
    - task: Docker@2
      displayName: Push Frontend Docker Image
      inputs:
        containerRegistry: 'classtrackapi'
        command: 'push'
        repository: 'classtrack-frontend'
        tags: latest

    # Deploy Frontend Container
    - task: AzureWebAppContainer@1
      displayName: Deploy Frontend Container
      inputs:
        azureSubscription: 'Azure for Students(8c757b97-b103-445f-9aa8-d6cff021ddcf)'
        appName: 'ClassTrack-Frontend'
        containers: classtrackapi.azurecr.io/classtrack-frontend:latest
        appSettings: '-Port 8081'